[api]
enabled = false
port = 54321
schemas = ["public", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 17

[studio]
enabled = false

[local_smtp]
enabled = false

[storage]
enabled = false

[auth]
enabled = false

[realtime]
enabled = false
