-- ============================================================
-- Migration 00016: absorbed into 00004
-- expedientes_select_all_authenticated policy defined in 00004
-- ============================================================
